{"timestamp":"2025-07-25T12:19:47.502703","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-25T12:19:47.503381","level":"info","event":"Filling up the DagBag from /home/ubuntu/airflow/dag/twitter_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-25T12:20:07.170817Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-25T12:20:07.176338Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-25T12:20:07.176478Z","level":"info","event":"Current task name:twitter_etl","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-25T12:20:07.177027Z","level":"info","event":"Dag name:tweet_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-25T12:20:07.177354Z","level":"info","event":"Dataset URL: https://www.kaggle.com/datasets/mmmarchetti/tweets-dataset","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-25T12:20:32.531110","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectionError","exc_value":"HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /kaggle-data-sets/503888/932257/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250725%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250725T122007Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=1577e7c327f4854f66ea67c8bef707011950c29d923e72bb4a7c2f97cda7444103e4f9002c215a90c674095b2aa2da58138519a6552430932002f9f69a6c7b74bf2b9e8c69aa7e6f587f37ce0ce9094b2411ab9841b6d93332b14b575e431116c1589898138a6d2d150826aef379ac74b450688897b80e22089a9017c4686d7f2d9cbb94178423f465a1aa77132563a797b6d158a2dd0c360462e7a34cccf10348720f49a9f6bc3669925e8630e0ba5471c2aafab1ab43709bed753fc7ca621123265d56557d7d961e5516ebae829cc97a5d7c50dc4ac6f59053debe46fea4da9d8371aaae233c39bd06c9dad299405c2b104445d604083c6d40f0520e4bd88f (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7c8b2a742810>: Failed to resolve 'storage.googleapis.com' ([Errno -3] Temporary failure in name resolution)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/ubuntu/airflow/dag/twitter_data.py","lineno":15,"name":"run_twitter_etl"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py","lineno":1664,"name":"dataset_download_files"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/kagglesdk/datasets/services/dataset_api_service.py","lineno":80,"name":"download_dataset"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/kagglesdk/kaggle_http_client.py","lineno":124,"name":"call"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/requests/sessions.py","lineno":724,"name":"send"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/requests/sessions.py","lineno":265,"name":"resolve_redirects"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/requests/adapters.py","lineno":700,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /kaggle-data-sets/503888/932257/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250725%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250725T122007Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=1577e7c327f4854f66ea67c8bef707011950c29d923e72bb4a7c2f97cda7444103e4f9002c215a90c674095b2aa2da58138519a6552430932002f9f69a6c7b74bf2b9e8c69aa7e6f587f37ce0ce9094b2411ab9841b6d93332b14b575e431116c1589898138a6d2d150826aef379ac74b450688897b80e22089a9017c4686d7f2d9cbb94178423f465a1aa77132563a797b6d158a2dd0c360462e7a34cccf10348720f49a9f6bc3669925e8630e0ba5471c2aafab1ab43709bed753fc7ca621123265d56557d7d961e5516ebae829cc97a5d7c50dc4ac6f59053debe46fea4da9d8371aaae233c39bd06c9dad299405c2b104445d604083c6d40f0520e4bd88f (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7c8b2a742810>: Failed to resolve 'storage.googleapis.com' ([Errno -3] Temporary failure in name resolution)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/requests/adapters.py","lineno":667,"name":"send"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPSConnection object at 0x7c8b2a742810>: Failed to resolve 'storage.googleapis.com' ([Errno -3] Temporary failure in name resolution)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/connection.py","lineno":753,"name":"connect"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -3] Temporary failure in name resolution","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/lib/python3.12/socket.py","lineno":963,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-25T12:20:35.641232Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-25T12:20:35.641619Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-25T12:20:35.641989Z","level":"info","event":"Task:<Task(PythonOperator): twitter_etl>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-25T12:20:35.642393Z","level":"info","event":"Failure caused by HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /kaggle-data-sets/503888/932257/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250725%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250725T122007Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=1577e7c327f4854f66ea67c8bef707011950c29d923e72bb4a7c2f97cda7444103e4f9002c215a90c674095b2aa2da58138519a6552430932002f9f69a6c7b74bf2b9e8c69aa7e6f587f37ce0ce9094b2411ab9841b6d93332b14b575e431116c1589898138a6d2d150826aef379ac74b450688897b80e22089a9017c4686d7f2d9cbb94178423f465a1aa77132563a797b6d158a2dd0c360462e7a34cccf10348720f49a9f6bc3669925e8630e0ba5471c2aafab1ab43709bed753fc7ca621123265d56557d7d961e5516ebae829cc97a5d7c50dc4ac6f59053debe46fea4da9d8371aaae233c39bd06c9dad299405c2b104445d604083c6d40f0520e4bd88f (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7c8b2a742810>: Failed to resolve 'storage.googleapis.com' ([Errno -3] Temporary failure in name resolution)\"))","chan":"stdout","logger":"task"}
